name: "Test"

on:
  pull_request:
    branches: [master]
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest
      shell: sh
    - run: devenv ci
    - run: devenv shell crystal spec
